### ISSUE TITLE
Invalid / expired internships

### ISSUE THREAD

**Issue by BALaka-18** [gcreddy42/hiring2020#261]
The following internships are invalid / currenlty inactive : 
1. **Mulberry** - Data Science and Analytics Internship      ❌
2. **HP** - Data Sciences and Machine Learning Intern       ❌

The following internship is only for Masters / PhD students : 
1. **Amazon** - Amazon Science

**Comment by gcreddy42** [comment]
Thanks for bringing this to my attention. Removed them.
