### ISSUE TITLE
Mobile friendly view

### ISSUE THREAD

**Issue by gcreddy42** [gcreddy42/hiring2020#61]
The file currently is not mobile friendly. I have attached an image of how it looks on mobile. Please share your ideas on how this can be improved.
![mobile](https://user-images.githubusercontent.com/33116884/77731248-ef803f80-6fd8-11ea-9a8b-0d5479a8e0de.png)

**Comment by KevinVII** [comment]
#62 
This pull request should fix the table to look better on mobile!

**Comment by WeileiZeng** [comment]
For README in github, there is no obvious way to make a mobile-friendly table. One alternative solution is enable github pages, then you can do whatever you want with the table with a web version. If you want to play with it, then you can play with it. A much easier solution is to introduce your project to https://stayinghome.club/ . I think they would be happy to spend 10 minutes to add a ( automatically updated) page for your site,

**Comment by Schemetrical** [comment]
Use ✅ and 🚫/❌ To reduce column width?

**Comment by gcreddy42** [comment]
@WeileiZeng That sounds like a good option. I would do it myself but it's getting difficult to keep up with the continuous updates. Will see what I can do.

**Comment by gcreddy42** [comment]
@Schemetrical It's a good idea but the main issue seems to be the 'Notes' column width, which is causing the other two columns to shrink.

**Comment by Schemetrical** [comment]
By the way gh pages with a theme automatically updates from the markdown file when done correctly. See https://github.com/wwdc/2019 and https://wwdc.github.io/2019/

**Comment by WeileiZeng** [comment]
I am thinking another idea that
* since you only have two types (canceled or not canceled). You can simply remove this column, because they already are in two tables
* Instead of using tables, using lists. A format would like the following

### Cancel intern
* company name, <descriptions if needed>
* more
* more
### Not Canceled intern
* this is one
* and another one, with more detail

Meanwhile, If you know the source of the information, it is better to add a link as well. For example
* [A company](https://example.com/amouncement) description

**Comment by WeileiZeng** [comment]
Some personal opinion for your reference.
It is fun to play with github pages. It allow you to do many things and make your data machine readable. The disadvantage of it, is that it require a second step for users to go to your github repo if they want to edit and send a pull request. For a project within one page/file, it is also a nice idea to keep it simple and within one place.

**Comment by WeileiZeng** [comment]
> @WeileiZeng That sounds like a good option. I would do it myself but it's getting difficult to keep up with the continuous updates. Will see what I can do.

The set up of github pages is easy. I don't think it require any coding for you. Just
* turn it on in Setting/Github Pages
* Choose a table-friendly theme, e.g. cayman
That is it! And it updates automatically.
But as I said, it adds a maybe-unnecessary page for your project.

**Comment by gcreddy42** [comment]
Thanks guys @Schemetrical @WeileiZeng . Your comments are very helpful. Will explore these options👍🏻

**Comment by wadefletch** [comment]
I'd like to add this data to [COVINTERN.com](COVINTERN.com) as a "status" page. Do you mind? It would be another slick way to view it on mobile.

**Comment by gcreddy42** [comment]
@wadefletch My only concern is people's contributions to this repo shouldn't stop. Currently, whenever people visit the list here, they also see a message saying they can contribute by making a pull request on the repo or by DMing me on Twitter. If we can ensure those contributions won't stop, then we are good. Why don't you drop me a message on Twitter, we can discuss how to ensure that.

**Comment by wadefletch** [comment]
DM'ed.

**Comment by gcreddy42** [comment]
> DM'ed.

Did you DM me on Twitter at '@hiring2020' . I can't find your message.

**Comment by wadefletch** [comment]
Yup! :)

**Comment by gcreddy42** [comment]
> Yup! :)

Due to some glitch I'm not able to receive DMs on Twitter. I reached out to you on Linkedin

**Comment by briancpark** [comment]
There are the official GitHub mobile app for Android and iOS. The README.md file is mobile friendly and properly scaled unlike the one you show in the picture. 

Android: [link](https://play.google.com/store/apps/details?id=com.github.android)
iOS and iPadOS: [link](https://apps.apple.com/us/app/github/id1477376905?ls=1)
